
## question2.1
```{R}
exp_data=read.csv("D:\\code\\UIUC_code\\R_code\\exp.csv",encoding="UTF-8",header=TRUE)
mean_e=mean(exp_data$sample)
lamda_hat=1/mean_e
theta=1/lamda_hat
theta
```
## question2.2
```{r}
var_s=var(exp_data$sample)
fisherinfor=length(exp_data$sample)*var_s
fisherinfor
# ese=1/sqrt(fisherinfor)
ese=lamda_hat/sqrt(nrow(exp_data))
ese
```

```{r}
lb=lamda_hat-qnorm(0.975)*ese
ub=lamda_hat+qnorm(0.975)*ese

lb
ub

```




## 3.question1
```{R}
data=read.csv("D:\\code\\UIUC_code\\R_code\\ZMTSLA.csv",encoding="UTF-8",header=TRUE)
log_ZM=log(data$ZM)
log_return=diff(log_ZM,lag=1)
Fhat=ecdf(log_return)
plot(Fhat,verticals=TRUE,do.points=FALSE)
```

## question2 compute sample kurtosis
```{r}
library(moments)

kurt=kurtosis(log_return,na.rm=TRUE)
kurt
```


## question3 resampling
```{R}
B=5000
n=length(log_return)
sample_medians=rep(0,B)
sample_means=rep(0,B)
sample_kurtosis=rep(0,B)
for(b in 1:B){
    xstar=sample(log_return,n,replace=TRUE)
    sample_medians[b]=median(xstar)
    sample_means[b]=mean(xstar)
    sample_kurtosis[b]=kurtosis(xstar)
}
hist(sample_kurtosis)
```

## question4 standard error
```{R}
library(plotrix)
std.error(sample_kurtosis)
sd=sd(sample_kurtosis)
sd
stderror=sd/sqrt(length(sample_kurtosis))
stderror
```

## question5 probability
```{r}
sample_7=sample_kurtosis[sample_kurtosis>=7]
probability=length(sample_7)/length(sample_kurtosis)
probability
```

## question6 95% confidence interval
```{r}
qu=quantile(sample_kurtosis,probs=0.975)
ql=quantile(sample_kurtosis,probs=0.025)

lowb=2*kurt-qu
upperb=2*kurt-ql
lowb
upperb
```
