## question1.1-2
```{r}
set.seed(1)
t=seq(1,100,by=1) #time
X  =10+t+rnorm(100)
Y1 =20+2*t+rnorm(100)
Y2 =20+2*t+5*X+rnorm(100)
data = data.frame(X,Y1,Y2)
ddata=data.frame(apply(data,2,diff))
# ddata
# data
fit1=lm(X~Y1)
fit2=lm(X~Y2)
summary(fit1)
summary(fit2)

dX=ddata$X
dY1=ddata$Y1
dY2=ddata$Y2
# pairs(cbind(dX,dY1,dY2))
fit3=lm(dX~dY1)
fit4=lm(dX~dY2)
summary(fit3)
summary(fit4)
```

## question2
```{r}
library(AER)
data("USMacroG")

dim(USMacroG)

USMacroG=na.omit(USMacroG)
dim(USMacroG)
# USMacroG
Macro=as.data.frame(apply(USMacroG,2,diff))
dim(Macro)

sum(is.na(USMacroG))
sum(is.na(Macro))
```

## question 2.1
```{r}
dConsumption=USMacroG[,"consumption"]
dCpi=USMacroG[,"cpi"]
dGdp=USMacroG[,"gdp"]
fit21=lm(dConsumption~dCpi)
summary(fit21)
ddConsumption=Macro$consumption
ddCpi=Macro$cpi
ddGdp=Macro$gdp
fit22=lm(ddConsumption~ddCpi)
summary(fit22)


```
## quetion 2.2
```{r}
plot(ddConsumption, ddGdp, main="Scatterplot Example",
xlab="consumption", ylab="gdp", pch=19)
fit23=lm(ddConsumption~ddGdp)
summary(fit23)
```

## quetion 2.3
```{r}
library(tidyverse)
library(ggpubr)

model <- lm(Macro$consumption ~ Macro$gdp)
model
fit24=lm(ddConsumption~ddGdp)
summary(fit24)

alpha=0.01
t=qt(1-alpha/2,200)
beta_gdp=0.39623
se=0.03038
lb=beta_gdp-t*se
ub=beta_gdp+t*se
lb



```

## question2.4
```{r}
anova(fit24)
```


## question2.5
```{r}

fit25 = lm(consumption ~ gdp, data=Macro[1:201,])

predict(fit25,Macro[202,],interval="predict")

```

## question2.6
```{r}
fit26=lm(Macro$consumption~Macro$tbill+Macro$inflation+Macro$cpi)
summary(fit26)
```

## question2.7
```{r}
fit27=lm(Macro$consumption~Macro$m1)
summary(fit27)
fit28=lm(Macro$consumption~Macro$m1+I(Macro$m1^2))
summary(fit28)

plot(Macro$m1,Macro$consumption)
lines(Macro$m1,fit27$fitted.values,lwd=3,col="red")
lines(sort(Macro$m1),fit28$fitted.values[order(Macro$m1)],lwd=3,col="blue")
legend("bottomright",c("Linear","Quadrratic"),col=c("red","blue"),lwd=3)
```

## question2.8
```{r}
fit29=lm(Macro$consumption~Macro$gdp+Macro$invest+Macro$government+
Macro$dpi+Macro$m1+Macro$tbill+Macro$inflation+Macro$cpi+Macro$unemp+Macro$population+
Macro$interest)
summary(fit29)
```